# Time in seconds
# Current in amps
# position, velocity, and acceleration in device units
steer_actuator:
  actuator_name: 'steer_actuator'
  serial_number: '602068008541'
  operation_mode: 'profile_position'
  clear_faults: true

  motor:
    type: 1
    dc_motor:
      nominal_current: 5.0
      max_output_current: 10.0
      thermal_time_constant: 41.5

  sensor:
    type: 1
    incremental_encoder:
      resolution: 500
      inverted_polarity: false

rear_left_drive_actuator:
  actuator_name: 'rear_left_drive_actuator'
  serial_number: '602068008479'
  operation_mode: 'profile_velocity'
  clear_faults: true

  motor:
    type: 1
    dc_motor:
      nominal_current: 5.0
      max_output_current: 10.0
      thermal_time_constant: 41.5

  sensor:
    type: 1
    incremental_encoder:
      resolution: 500
      inverted_polarity: false
