my_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

my_position_controller:
  type: position_controllers/JointPositionController
  joint: front_steer_joint

my_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rear_drive_joint
