# Time in seconds
# Current in amps
# position, velocity, and acceleration in device units
# COB-ID like "0x6402-00" is specified in "EPOS 2 Firmware Specification"
front_left_drive_actuator:
  actuator_name: 'front_left_drive_actuator'
  serial_number: '602068008501'
  operation_mode: 'profile_velocity'
  clear_faults: true

  motor:
    type: 1 # The type of the motor (0x6402-00)
    dc_motor:
      nominal_current: 5.0 # The max continuous motor current in amps (0x6410-01)
      max_output_current: 10.0 # The max peak current in amps (0x6410-02)
      thermal_time_constant: 41.5 # The thermal time constant in seconds (0x6410-05)

  sensor:
    type: 1 # The type of the sensor (0x2210-02)
    incremental_encoder:
      resolution: 1000 # The resolution of the encoder (0x2210-01)
      inverted_polarity: false # If the encoder is inverted from the motor (0x2210-04)

rear_drive_actuator:
  actuator_name: 'rear_drive_actuator'
  serial_number: '602068008425'
  operation_mode: 'profile_velocity'
  clear_faults: true

  motor:
    type: 1
    dc_motor:
      nominal_current: 5.0
      max_output_current: 10.0
      thermal_time_constant: 41.5

  sensor:
    type: 1
    incremental_encoder:
      resolution: 1000
      inverted_polarity: false

front_steer_actuator:
  actuator_name: 'front_steer_actuator'
  serial_number: '602068008332'
  operation_mode: 'profile_position'
  clear_faults: true
  
  motor:
    type: 11
    ec_motor:
      nominal_current: 2.77
      max_output_current: 10.0
      thermal_time_constant: 40.0
      number_of_pole_pairs: 7
  
  sensor:
    type: 2
    incremental_encoder:
      resolution: 1024
      inverted_polarity: true
    hall_sensor:
      inverted_polarity: true
